### PR TITLE
Create sage for conda with sirocco

### PR DESCRIPTION
**Pull request by enriqueartal**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)

I am not sure if I did it correctly. I am trying to introduce an optional package (sirocco), since it is not of universal use I wonder if  a different name should be chosen for the package.

### CODE REVIEW

**Comment by saraedum** [comment]
@enriqueartal could you explain what you are trying to achieve?

We can't change the name of the `sage` package, so we won't be able to merge this.

The package you are proposing is no different from installing `sage` and `sirocco` from conda-forge. Why would you want a specific package that bundles the two?

**Comment by enriqueartal** [comment]
> @enriqueartal could you explain what you are trying to achieve?
> 
I want to have sage on binder with optional packages, in this example, sirocco. I made several tries editing `environment.yml` withour success.
> We can't change the name of the `sage` package, so we won't be able to merge this.

Actually, I changed the name since I did not want to interfere with the sage package, since most probably it was not the right way to proceed.
> 
> The package you are proposing is no different from installing `sage` and `sirocco` from conda-forge. Why would you want a specific package that bundles the two?

Because of my ignorance, I do not know how to get the optional package in conda-forge and binder.
Thanks for your patience

**Comment by saraedum** [comment]
No worries. If you add `sirocco` to this https://github.com/sagemath/sage-binder-env/blob/master/environment.yml it should work. (Assuming sirocco is packaged on conda-forge?)

**Comment by saraedum** [comment]
sirocco does not seem to be packaged on conda-forge. Somebody would need to contribute a package to conda-forge for this before it can be used on binder.

It would be great if you could contribute that package. It's not all that hard, please see https://github.com/conda-forge/staged-recipes#getting-started

**Comment by saraedum** [comment]
I'm closing this pull request. Please feel free to continue the discussion if you have further questions though.

**Comment by enriqueartal** [comment]
I am following the instructions for the recipe and for the compilation of sirocco. For sirocco I should start with `./configure --prefix=<sagedir>/local --libdir=<sagedir>/local/lib`; which is `sagedir` in conda-forge sage installation?

**Comment by isuruf** [comment]
Use `./configure --prefix=$PREFIX --libdir=$PREFIX/lib`

**Comment by enriqueartal** [comment]
> 

I did it and it passes all the checks. Which is the following step?

**Comment by isuruf** [comment]
Send a PR to https://github.com/conda-forge/staged-recipes/

**Comment by enriqueartal** [comment]
I did it, after some mistakes the pull request passed all the tests.

**Comment by isuruf** [comment]
Now that there's a `sirocco` conda package, we need to build `sagelib` with `sirocco`. Can you send a PR to https://github.com/conda-forge/sagelib-feedstock ?

**Comment by enriqueartal** [comment]
First, Fernando @isuruf, thanks for your help. The package sirocco is optional, I will do the PR but if it is rejected there is no problem, maybe the goal is to keep sagelib and sage not so big in conda. Anyway, using sage-feedstock and sirocco it is possible to have a working binder image for sirocco. It may be usefui to have another optional packages as gap_packages. If I have time I may be give a try.

**Comment by saraedum** [comment]
@enriqueartal sagelib needs to build some glue code, namely [sirocco.pyx](https://github.com/sagemath/sage/blob/develop/src/sage/libs/sirocco.pyx) for sirocco to work fully I guess.

I agree that we should not aim to ship all optional dependencies with the sagelib package, however, we could build against sirocco but not actually add sirocco as a `run` dependency. So the code that uses sirocco would only work if sirocco is installed additionally.

> Anyway, using sage-feedstock and sirocco it is possible to have a working binder image for sirocco.

I am surprised that that works. How is this possible if the `sirocco.pyx` had not been compiled?

**Comment by enriqueartal** [comment]
You are completely right. I tried with a toy example which actually did not use sirocco. I will do the PR.

**Comment by slel** [comment]
For reference the PR is:

- Add sirocco package to conda
  https://github.com/conda-forge/staged-recipes/pull/19894

**Comment by enriqueartal** [comment]
This PR has been accepted, I created a new one to include sirocco in sagelib-feedstock but for some unknown reason sirocco is not found.

**Pull request closed without merging**
