### PR TITLE
Upgrade to 8.1

### LINKED ISSUE #3: Build on osx
- [ ] Patch cython for https://github.com/cython/cython/pull/466
- [ ] Use code from https://trac.sagemath.org/ticket/22554

### PR DESCRIPTION
**Pull request by saraedum**
Fixes #3, #10.

### CODE REVIEW

**Comment by saraedum** [comment]
How does the list of dependencies work here? It seems to be mostly `sagelib`, `sagemath-db-*` and their dependencies recursively. Why do we mention all those indirect dependencies explicitly in the recipe?

**Comment by isuruf** [comment]
> It seems to be mostly sagelib, sagemath-db-* and their dependencies recursively.

It's not. `sagelib` has mostly C/C++/Fortran libraries + compiled python packages. Pure python libraries like `mpmath, sympy`, etc are not dependencies of `sagelib`. I kept all the dependencies here because dependencies of sagelib change frequently and I didn't want to check which were coming in indirectly and everytime there's a release. If you have free time, it's okay to remove indirect dependencies here, but I wouldn't waste time on it.

**Comment by saraedum** [comment]
Ok. I found this very confusing. I think I'll try to document this in more detail.

**Comment by saraedum** [comment]
@isuruf: Why is the CI skipping everything? This should just fail since sagelib is not available in the correct version yet.

**Comment by saraedum** [comment]
@isuruf: So what's the line between a dependency of sagelib and a dependency of sage? Should the sagelib dependencies be only such that I can import sage.all without errors? Or should all of sage actually work without weird errors with just the sagelib dependencies?

**Comment by isuruf** [comment]
I used the dependencies of sagelib as in the Makefile. I separated sagelib and sage because there were packages (database packages) that were dependencies of sage, but needed the sagelib (python package) to build.

**Comment by saraedum** [comment]
Hm…I understand what you are saying but I do not really understand what that means for runtime dependencies now. Sure, packages that need sagelib to build should probably not be runtime dependencies of sagelib. Are the runtime dependencies of sagelib then just the runtime dependencies of sage that are also build-time dependencies of sagelib? So in other words this is mostly about keeping track of the pinnings in the same recipe?
I am fine with that rule but I would like to document it somewhere and put the information somewhere that `sagelib` is good enough to `import sage` but that many things won't work until you also install `sage`.

**Comment by isuruf** [comment]
The runtime dependencies of sagelib are those described in `build/make/Makefile`
```
# Everything needed to start up Sage using "./sage".  Of course, not
# every part of Sage will work.  It does not include Maxima for example.
SAGERUNTIME = sagelib $(SCRIPTS) $(inst_ipython) $(inst_pexpect) \
		$(inst_psutil) $(inst_future)
```

**Comment by isuruf** [comment]
I should have mentioned this earlier, but I had forgotten that.

**Comment by saraedum** [comment]
@isuruf For some reason the CIs only try to build this for py36 and then skip it.

**Comment by isuruf** [comment]
Can you try adding python to build requirements and do a rerender?

**Comment by saraedum** [comment]
@conda-forge-admin, please rerender

**Comment by isuruf** [comment]
Requires solving https://github.com/conda-forge/linbox-feedstock/issues/3

**Comment by saraedum** [comment]
Do I need make a trivial push or is there some way to rerun CI so it can pick up the new version of linbox?

**Comment by isuruf** [comment]
You should have permissions to rerun on travis-ci. For circle-ci, you have to be a maintainer of the feedstock

**Comment by saraedum** [comment]
@conda-forge-admin, please rerender

**Comment by saraedum** [comment]
Looks good to me @isuruf.

**Comment by isuruf** [comment]
Should we add r-base>=3.4.2? It seems to be installing an older version

**Comment by saraedum** [comment]
Should we maybe do that in a followup PR? What's the general policy? We want at least the version that Sage has for every dependency?

**Comment by isuruf** [comment]
> Should we maybe do that in a followup PR?

sure

>We want at least the version that Sage has for every dependency?

Sounds good to me

**Pull request merged**
