### PR TITLE
Upgrade to 10.2

### PR DESCRIPTION
**Pull request by saraedum**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

##### Dependencies 

* [x] sage 10.1, https://github.com/conda-forge/sage-feedstock/pull/94
* [x] sagelib 10.2 https://github.com/conda-forge/sagelib-feedstock/pull/165
* [x] Upgrade arb 2.22.1→2.23.0
* [x] Upgrade attrs 22.1.0→23.1.0 (indirect or distribution dependency)
* [x] Upgrade babel 2.11.0→2.12.1
* [x] Add cachetools 5.3.1 (indirect or distribution dependency)
* [x] Add calver 2022.6.26 (distribution dependency)
* [x] Upgrade certifi 2022.9.24→2023.7.22
* [x] Add chardet 5.2.0 (tox dependency)
* [x] Upgrade cmake 3.24.3→3.27.3 (indirect or distribution dependency)
* [x] Add colorama 0.4.6 (tox dependency)
* [x] Upgrade configure  (indirect or distribution dependency)
* [x] Upgrade contourpy 1.0.6→1.1.1 (indirect or distribution dependency)
* [ ] Upgrade cypari 2.1.3→2.1.4 needs https://github.com/sagemath/cypari2/issues/143 and then a PR on the cypari feedstock
* [ ] Upgrade cysignals 1.11.2→1.11.4 https://github.com/conda-forge/cysignals-feedstock/pull/50 needs https://github.com/sagemath/cysignals/issues/195
* [x] Upgrade cython 0.29.32.p2→3.0.4
* [x] Upgrade distlib 0.3.6→0.3.7 (indirect or distribution dependency)
* [x] Upgrade editables 0.3→0.5 (indirect or distribution dependency)
* [x] Upgrade fastjsonschema 2.16.2→2.18.0 (indirect or distribution dependency)
* [x] Upgrade filelock 3.8.0→3.12.3 (indirect or distribution dependency)
* [x] Upgrade flint 2.8.4→2.9.0
* [x] Upgrade flit_core 3.7.1→3.9.0 (indirect or distribution dependency)
* [x] Upgrade fonttools 4.28.4→4.42.1 (indirect or distribution dependency)
* [x] Upgrade fplll 5.4.4→5.4.5
* [x] Upgrade fpylll 0.5.9→0.6.0
* [x] Upgrade gast 0.5.3→0.5.4 (indirect or distribution dependency)
* [x] Upgrade gc 8.0.4→8.2.4 (indirect or distribution dependency)
* [x] Upgrade hatch_fancy_pypi_readme 22.8.0→23.1.0 (indirect or distribution dependency)
* [x] Upgrade hatch_vcs 0.2.0→0.3.0 (indirect or distribution dependency)
* [x] Upgrade hatchling 1.11.1→1.18.0 (indirect or distribution dependency)
* [x] Upgrade importlib_metadata 6.0.0→6.8.0 (indirect or distribution dependency)
* [x] Upgrade importlib_resources 5.12.0→6.0.1 (indirect or distribution dependency)
* [x] Add ipympl 0.9.3 (optional)
* [x] Upgrade jupyter_core 4.11.2→4.12.0
* [x] Upgrade jupyter_sphinx 0.3.2→0.4.0.p0 (indirect or distribution dependency)
* [x] Upgrade kissat 3.0.0→3.1.0 (optional)
* [x] Upgrade kiwisolver 1.4.3→1.4.5 (indirect or distribution dependency)
* [x] Upgrade libatomic_ops 7.6.10→7.8.0 (indirect or distribution dependency)
* [x] Upgrade libbraiding 1.1→1.2 https://github.com/conda-forge/libbraiding-feedstock/pull/4
* [x] Upgrade markupsafe 2.1.1→2.1.3 (indirect or distribution dependency)
* [x] Upgrade matplotlib 3.6.2→3.8.0
* [x] Upgrade meson 1.0.1→1.2.3 (indirect or distribution dependency)
* [x] Upgrade meson_python 0.12.1→0.14.0 (indirect or distribution dependency)
* [x] Upgrade msolve 0.4.9→0.5.0 (optional)
* [x] Upgrade nauty 27r1.p1→2.8.6.p1 https://github.com/conda-forge/nauty-feedstock/pull/22
* [x] Upgrade ninja_build 1.11.0→1.11.1 (indirect or distribution dependency)
* [x] Upgrade normaliz 3.10.0→3.10.1 (optional)
* [x] Upgrade numpy 1.23.5→1.26.1
* [x] Upgrade onetbb 2021.7.0→2021.9.0 (optional)
* [x] Upgrade openblas 0.3.23→0.3.25 (done differently)
* [x] Upgrade openssl 3.0.8→3.0.12 (indirect or distribution dependency)
* [x] Upgrade packaging 21.3→23.2 (indirect or distribution dependency)
* [x] Upgrade pari 2.15.2.p1→2.15.4
* [x] Upgrade pillow 9.0.1→10.1.0
* [x] Upgrade pip 22.3.1→23.3.1 (indirect or distribution dependency)
* [x] Upgrade platformdirs 2.5.4→3.11.0 (indirect or distribution dependency)
* [x] Upgrade pluggy 1.0.0→1.3.0 (indirect or distribution dependency)
* [x] Upgrade pplpy 0.8.7→0.8.9 https://github.com/conda-forge/pplpy-feedstock/pull/14
* [x] Upgrade ptyprocess 0.5.1.p0→0.7.0
* [x] Upgrade pybind11 2.10.1→2.11.1 (indirect or distribution dependency)
* [x] Upgrade pyparsing 3.0.9→3.1.1
* [x] Add pyproject_api 1.6.1 (tox dependency)
* [x] Upgrade pyproject_metadata 0.6.1→0.7.1 (indirect or distribution dependency)
* [x] Upgrade pythran 0.12.1→0.14.0
* [x] Upgrade pytz 2022.5→2023.3.post1
* [x] Upgrade pyzmq 24.0.1→25.1.1
* [x] Upgrade scipy 1.10.1→1.11.3
* [x] Upgrade send2trash 1.8.0→1.8.2 (indirect or distribution dependency)
* [x] Upgrade setuptools 63.4.3→68.2.2 (indirect or distribution dependency)
* [x] Upgrade setuptools_scm 7.0.5→8.0.4 (indirect or distribution dependency)
* [x] Upgrade singular 4.3.1p3→4.3.2p8 https://github.com/conda-forge/singular-feedstock/pull/25
* [x] Upgrade tox 3.27.0→4.11.1 (indirect or distribution dependency)
* [x] Upgrade traitlets 5.5.0→5.9.0
* [x] Add trove_classifiers 2023.8.7 (hatchling dependency)
* [x] Upgrade typing_extensions 4.5.0→4.7.1 (indirect or distribution dependency)
* [x] Upgrade tzlocal 4.2→5.0.1 (indirect or distribution dependency)
* [x] Upgrade virtualenv 20.16.6→20.24.4 (indirect or distribution dependency)
* [x] Upgrade wheel 0.38.4→0.41.2 (indirect or distribution dependency)
* [x] Upgrade widgetsnbextension 4.0.3→4.0.8
* [x] Upgrade zeromq 4.3.4→4.3.5

### CODE REVIEW

**Comment by saraedum** [comment]
@conda-forge-admin, please rerender

**Comment by saraedum** [comment]
Let's see if the missing upgrades are actually necessary.

**Comment by isuruf** [comment]
```
File "src/sage/interfaces/singular.py", line 1265, in sage.interfaces.singular.Singular.version
Failed example:
    singular.version()
Exception raised:
    Traceback (most recent call last):
      File "$PREFIX/lib/python3.11/site-packages/sage/doctest/forker.py", line 709, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "$PREFIX/lib/python3.11/site-packages/sage/doctest/forker.py", line 1144, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.interfaces.singular.Singular.version[0]>", line 1, in <module>
        singular.version()
      File "$PREFIX/lib/python3.11/site-packages/sage/interfaces/singular.py", line 1268, in version
        return singular_version()
               ^^^^^^^^^^^^^^^^^^
      File "$PREFIX/lib/python3.11/site-packages/sage/interfaces/singular.py", line 2464, in singular_version
        return singular.eval('system("--version");')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "$PREFIX/lib/python3.11/site-packages/sage/interfaces/singular.py", line 667, in eval
        raise SingularError('Singular error:\n%s' % s)
    sage.interfaces.singular.SingularError: Singular error:
    *** stack smashing detected ***: $PREFIX/bin/Singular terminated
    Singular : signal 11 (v: 4212):
    current line:>>system("--version");<<
    Segment fault/Bus error occurred at 7fff8374f970 because of 10246 (r:101047404)
    please inform the authors
    trying to restart...
**********************************************************************
```

**Comment by saraedum** [comment]
Unsurprisingly, running `system("--version");` directly in our singular works fine on my machine.

**Comment by saraedum** [comment]
Hm…but we pulled in `    singular:                          4.2.1.p3-h1ea75ed_2        conda-forge` instead of the latest version.

**Comment by saraedum** [comment]
I guess we need a singular built against an old FLINT here.

**Comment by saraedum** [comment]
@isuruf, I cannot reproduce the Singular error locally. Apart from that, Singular seems to work fine since lots of tests that rely on it do pass.

**Pull request merged**
