### PR TITLE
update to 9.3

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by isuruf** [comment]
This is a package with 100+ direct dependencies and 300+ indirect dependencies. It's also a meta-package that is noarch. (code is in `sagelib` conda package which has minimal deps and is used for building a few dependencies of `sage` and then `sage` is just a collection of `sagelib` package and other dependencies)

@conda-forge/core, this package doesn't build with conda-build, but does with conda-mambabuild. Since it's noarch, is it okay to use conda-mambabuild here? (I've tried debugging, but it's hard given that there are 300+ indirect dependencies)

**Comment by beckermr** [comment]
I'd be ok making an exception, but you'll have to edit the build scripts by hand. Smithy doesn't support uploads from mamba build.

**Comment by isuruf** [comment]
> I'd be ok making an exception,

Thanks.

> but you'll have to edit the build scripts by hand. Smithy doesn't support uploads from mamba build.

Sure. This should be a temporary measure and I'll try to debug it in the future.

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Pull request merged**
