### PR TITLE
Allow wider range of versions for Tornado

### PR DESCRIPTION
**Pull request by slel**
As suggested at https://github.com/conda-forge/sage-feedstock/issues/55#issuecomment-662107761

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by slel** [comment]
@conda-forge-admin, please rerender

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by slel** [comment]
Regarding the "Ensured the license file is being packaged"
checkbox, Sage has a file `COPYING.txt` here:
- https://github.com/sagemath/sage/blob/develop/COPYING.txt
Is that satisfactory enough to tick the checkbox?

**Comment by nthiery** [comment]
Thank you @slel and @isuruf for working on this!

**Comment by isuruf** [comment]
That's fine for now. This is a meta-package and doesn't have any code distributed.

**Comment by isuruf** [comment]
Thanks for the PR @slel. @nthiery, please check after a couple of hours to see if this fixes your problem.

**Pull request merged**
